CREATE TABLE post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
    content    VARCHAR(255)                                          NOT NULL,
    account_id    BIGINT                                                NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE account
(
    account_id    BIGINT GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
    username   VARCHAR(255)                                          NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (account_id)
);

ALTER TABLE account
    ADD CONSTRAINT uc_account_username UNIQUE (username);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (account_id);
