CREATE TABLE accountAttribute
(
    openIDGoogleID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(60) NOT NULL,
    firstName VARCHAR(20) NOT NULL,
    account_id BIGINT NOT NULL,
    CONSTRAINT pk_attribute PRIMARY KEY (openIDGoogleID)
);

ALTER TABLE accountAttribute
    ADD CONSTRAINT FK_ATTRIBUTE_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (account_id);