CREATE TABLE account
(
    account_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(255)                            NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    image          BYTEA,
    breed          VARCHAR(100),
    google_oidc2id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (account_id)
);

ALTER TABLE account
    ADD CONSTRAINT uc_account_googleoidc2id UNIQUE (google_oidc2id);

ALTER TABLE account
    ADD CONSTRAINT uc_account_username UNIQUE (username);

-- Add unique index for performance optimization
CREATE UNIQUE INDEX idx_account_google_oidc2_id ON account (google_oidc2id);
