CREATE TABLE google_account_api_key_link
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    google_oidc2id VARCHAR(255)                                  NOT NULL,
    CONSTRAINT pk_google_account_api_key_link PRIMARY KEY (id),
    CONSTRAINT fk_gaakl_account_google_oidc2_id FOREIGN KEY (google_oidc2id) REFERENCES account (google_oidc2id)
);

ALTER TABLE google_account_api_key_link
    ADD CONSTRAINT uc_google_account_api_key_link_google_oidc2 UNIQUE (google_oidc2id);
