CREATE TABLE issued_api_key
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hashed_api_key                 VARCHAR(255)                            NOT NULL,
    issued_at                      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at                     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked                        BOOLEAN                                 NOT NULL,
    last_used_at                   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    api_key_name                   VARCHAR(255)                            NOT NULL,
    google_account_api_key_link_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_issued_api_key PRIMARY KEY (id)
);

ALTER TABLE issued_api_key
    ADD CONSTRAINT uc_issued_api_key_hashedapikey UNIQUE (hashed_api_key);

ALTER TABLE issued_api_key
    ADD CONSTRAINT FK_ISSUED_API_KEY_ON_GOOGLE_ACCOUNT_API_KEY_LINK FOREIGN KEY (google_account_api_key_link_id) REFERENCES google_account_api_key_link (id);
