name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 24

      - name: Compile with Maven
        run: mvn -B --no-transfer-progress compile --file pom.xml

      - name: Run test with Maven
        run: mvn -B --no-transfer-progress verify --file pom.xml