name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 24
          cache: 'maven'

      - name: Set environment variables
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: echo "Environment variables set"

      - name: Compile with Maven
        run: mvn -B --no-transfer-progress compile --file pom.xml

      - name: Run test with Maven
        run: mvn -B --no-transfer-progress verify --file pom.xml
